<div id="content">
	<h5 class="side_title">Condiciones de uso</h5>

	<div class="text silver_box static_page">
		<p>
			&#218;ltima actualizaci&#243;n: 30 de abril de 2015
			<br /><br /><br />
			<strong>Introducci&#243;n : </strong>
			ValueBasket.com Limited (ValueBasket.com) le proporciona caracter&#237;sticas del portal web bajo las siguientes condiciones. Por favor, lea atentamente nuestra p&#225;gina web. Al visitar o realizar compras en ValueBasket.com se compromete a aceptar y respetar las siguientes condiciones de uso, que incluyen otras condiciones publicadas en este portal web y que son susceptibles de sufrir modificaciones con el tiempo.
			<br /><br />
			<strong>Privacidad : </strong>
			Por favor revise nuestra <a href="[base_url;noerr;]privacy_policy">Pol&#237;tica de privacidad</a> en la que encontrar&#225; informaci&#243;n de nuestras pr&#225;cticas aplicables al uso de nuestro portal web.
			<br /><br />
			<strong>Propiedad intelectual : </strong>
			Todo el contenido de nuestro portal web (incluyendo textos, gr&#225;ficos, logotipos, iconos de botones, im&#225;genes, clips de audio, descargas digitales, compilaciones de datos y software) y la compilaci&#243;n de todo el contenido de tal manera que se utiliza en este sitio web es propiedad de ValueBasket.com o de sus proveedores de contenido y est&#225; protegido por las leyes de propiedad intelectual aplicables.
			<br /><br />
			<strong>Aviso de marca registrada : </strong>
			ValueBasket.com es nuestra marca registrada y no puede ser utilizada en relaci&#243;n a ning&#250;n otro producto o servicio que no pertenezca a ValueBasket.com o que pueda causar confusi&#243;n entre los clientes o de alguna manera que menosprecie o desacredite a ValueBasket.com. Las mismas restricciones de uso se aplican a las dem&#225;s marcas que no pertenecen a ValueBasket.com y que aparecen en nuestro portal web, pero que son propiedad de sus respectivos due&#241;os, quienes pueden o no tener relaci&#243;n con ValueBasket.com.
			<br /><br />
			<strong>Comunicaciones electr&#243;nicas : </strong>
			Cuando visite o env&#237;e e-mails a ValueBasket.com, se est&#225; comunicando con ValueBasket.com electr&#243;nicamente. Usted da su consentimiento para recibir comunicaciones de ValueBasket.com electr&#243;nicamente. ValueBasket.com se comunicar&#225; con usted por correo electr&#243;nico o mediante la publicaci&#243;n de avisos en la p&#225;gina web ValueBasket.com. Usted acepta que todas las condiciones, acuerdos, avisos, divulgaciones y otras comunicaciones proporcionadas electr&#243;nicamente satisfacen cualquier requisito de que dichas comunicaciones sean por escrito.
			<br /><br />
			<strong>Licencia de uso y acceso al portal : </strong>
			ValueBasket.com otorga una licencia limitada para acceder y hacer uso personal del portal y proh&#237;be cualquier descarga (con excepci&#243;n de caching de p&#225;ginas) o la modificaci&#243;n de alguna o todas, excepto en el caso de que se exprese consentimiento previo por escrito de ValueBasket.com. Esta licencia no incluye cualquier recopilaci&#243;n, uso, reventa o uso comercial de este portal web o de su contenido, cualquier uso derivado de este portal o de su contenido, cualquier descarga o copia de informaci&#243;n de cuenta para beneficio de otra persona, o cualquier uso de cualquier recopilaci&#243;n de datos y herramientas de extracci&#243;n. Este portal web, o cualquiera de sus partes, no se podr&#225; reproducir, duplicar, copiar, vender, revender, visitar o explotar para cualquier prop&#243;sito comercial sin el expreso consentimiento previo por escrito de ValueBasket.com. No est&#225; permitido enmarcar o utilizar t&#233;cnicas de enmarcado para adjuntar cualquier marca, logotipo, u otra informaci&#243;n propietaria (incluyendo im&#225;genes, texto, dise&#241;o de p&#225;gina, o forma) de ValueBasket.com sin el consentimiento expreso por escrito de ValueBasket.com. De igual manera no se permite utilizar cualquier meta-etiquetas o cualquier otro texto oculto que puede tener referencia al nombre ValueBasket.com u otras marcas comerciales sin el consentimiento expreso y por escrito de ValueBasket.com. Cualquier uso no autorizado conllevar&#225; la revocaci&#243;n del permiso otorgado por ValueBasket.com para el uso de la web. Se le concede un derecho limitado, revocable y no exclusivo para crear y mantener un hiperv&#237;nculo a la p&#225;gina de inicio de ValueBasket.com s&#243;lo cuando este v&#237;nculo no represente ValueBasket.com, sus productos o servicios de una manera falsa, enga&#241;osa, despectiva o de manera ofensiva. No est&#225; permitido el uso de ning&#250;n logotipo u otro gr&#225;fico de ValueBasket.com o marca registrada como parte del enlace sin el permiso expreso y por escrito de ValueBasket.com.
			<br /><br />
			<strong>Cumplimiento : </strong>
			ValueBasket.com se reserva el derecho de investigar y denunciar cualquier violaci&#243;n de las Condiciones de Uso, al hacerlo, ValueBasket.com puede solicitar la cooperaci&#243;n de las autoridades legales para perseguir a los usuarios. Usted reconoce que ValueBasket.com no tiene obligaci&#243;n de controlar el acceso o uso del portal web ValueBasket.com, pero se reserva el derecho de hacerlo para fines de operar el portal web ValueBasket.com, pero se reserva el derecho de hacerlo para asegurar el cumplimiento de las Condiciones de Uso o para cumplir con la ley aplicable, orden o requerimiento de un tribunal, agencia administrativa u organismo gubernamental.
			<br /><br />
			<strong>Mi cuenta : </strong>
			Se reserva el uso de ValueBasket.com s&#243;lo para adultos y mediante el uso de la p&#225;gina web de ValueBasket.com manifiesta y garantiza que tiene al menos 18 a&#241;os. Si usted es menor de 18 a&#241;os, no utilice, acceda o se registre en ValueBasket.com. Al utilizar el portal web, ValueBasket.com requiere registrarse y crear una cuenta de usuario. Usted acepta como una condici&#243;n de uso y de registro que podamos contactarle para informarle de posibles cambios en las condiciones de uso o para informarle de nuevos servicios disponibles en ValueBasket.com.
			<br /><br />
			Usted es responsable de mantener la confidencialidad de todas las actividades que ocurran bajo su cuenta y contrase&#241;a. Tambi&#233;n acepta la responsabilidad de restringir el acceso a ordenador y se compromete a notificar inmediatamente a ValueBasket.com de cualquier violaci&#243;n de seguridad de su cuenta. ValueBasket.com no ser&#225; responsable de ninguna p&#233;rdida derivada del uso no autorizado de su cuenta.
			<br /><br />
			ValueBasket.com se reserva el derecho de negar el servicio, cancelar cuentas, quitar o editar contenido, o cancelar pedidos en ValueBasket.com sin tener que dar una justificaci&#243;n. Usted podr&#225; cancelar su cuenta en cualquier momento a trav&#233;s de la informaci&#243;n encontrada en nuestra p&#225;gina <a href="[base_url;noerr;]contact">Cont&#225;ctenos</a> 
			<br /><br />
			<strong>Descripci&#243;n del producto : </strong>
			En ValueBasket.com hacemos todo lo posible para que nuestras descripciones de producto sean lo m&#225;s precisas. Sin embargo, ValueBasket.com no garantiza que la descripci&#243;n del producto u otro contenido encontrado en el portal web sea exacta, completa, fiable, actual o libre de errores. Si usted recibe un producto de ValueBasket.com que no cumple con lo especificado en el portal web, su &#250;nico remedio es devolverlo sin utilizarlo de acuerdo con nuestras Condiciones de Cancelaci&#243;n, Devoluciones y Reembolsos.
			<br /><br />
			<strong>Precios : </strong>
			ValueBasket.com no puede confirmar el precio de un art&#237;culo hasta que realice su pedido. Pese a que ValueBasket.com hace todo lo posible para que nuestros precios sean precisos, algunos art&#237;culos en nuestro portal web pueden encontrarse infravalorados. En el supuesto de que el precio correcto de un art&#237;culo sea m&#225;s alto que el precio del pedido, ValueBasket.com, seg&#250;n considere m&#225;s conveniente se pondr&#225; en contacto con usted para darle m&#225;s informaci&#243;n o cancelar&#225; su pedido y le informar&#225; posteriormente de la cancelaci&#243;n.
			<br /><br />
			<strong>Informaci&#243;n del pedido e importaci&#243;n : </strong>
			Al realizar un pedido con ValueBasket.com, usted acepta toda la responsabilidad de asegurar que su compra se puede importar de conformidad con las leyes del pa&#237;s al que usted ha solicitado ValueBasket.com enviar su compra. De igual modo acepta ser el importador exclusivo de su compra a todos los efectos, incluyendo, pero no limitado a las regulaciones de aduana, propiedad intelectual, normativa de marca registrada y se compromete a cumplir con todas las leyes y regulaciones del pa&#237;s en el que se recibe la mercanc&#237;a. Para ello, el usuario reconoce y acepta que el papel de ValueBasket.com se limita a la adquisici&#243;n de los productos comprados en Hong Kong y otras regiones y la elaboraci&#243;n de estos productos est&#225; disponible a trav&#233;s de la p&#225;gina web para la venta en Hong Kong y para su importaci&#243;n a su pa&#237;s. En ning&#250;n caso ValueBasket.com ser&#225; parte en la importaci&#243;n de dichos productos ni ValueBasket.com ser&#225; responsable de cualquier obligaci&#243;n que surja en virtud de las leyes de cualquier pa&#237;s que no sea Hong Kong para la importaci&#243;n y venta de productos disponibles en el portal web, incluyendo, sin normas de limitaci&#243;n de aduanas y costumbres se mantiene, las retenciones e incautaciones, leyes de propiedad intelectual y marca registrada. Los clientes de fuera de Hong Kong autorizan a ValueBasket.com a hacer los tr&#225;mites necesarios para llevar a cabo el despacho de aduanas en su nombre por las compras realizadas. Los procedimientos de despacho de aduana podr&#225;n suponer la apertura e inspecci&#243;n del paquete en env&#237;os transfronterizos.
			<br /><br />
			<strong>Importaci&#243;n, impuestos y cargos : </strong>
			Los aranceles de importaci&#243;n e impuestos (directa e indirectamente relacionados) son aplicables a los env&#237;os en el extranjero fuera de Hong Kong. Normalmente el destinatario ser&#225; el encargado de satisfacer todas las obligaciones derivadas de la importaci&#243;n tales como aranceles y otros impuestos que ser&#225;n calculados a partir de la factura comercial. De igual manera, pueden existir sobrecargos y otros impuestos indirectos que depender&#225;n de las diferentes pol&#237;ticas aduaneras alrededor del mundo. La pol&#237;tica aduanera es diferente en cada pa&#237;s por lo que se debe contactar con la oficina local de aduanas para conocer m&#225;s informaci&#243;n sobre la normativa aplicable. ValueBasket.com no tiene control sobre las obligaciones aduaneras e impuestos. Para algunos pa&#237;ses de destino ser&#225; aplicable un sobrecargo en concepto de tramitaci&#243;n de aduanas que se incluir&#225; en la factura de env&#237;o. Cuando una tasa de tramitaci&#243;n de importaci&#243;n se incluya, ValueBasket.com ser&#225; responsable de los impuestos y aranceles directamente relacionados con el pedido facturado. llevar&#225; la responsabilidad por los impuestos y derechos que s&#243;lo est&#225;n directamente relacionadas con el orden facturado. Cualquier tasa de tramitaci&#243;n de importaci&#243;n que figuran en el aviso de env&#237;o no es reembolsable. Si devuelve el producto dentro de los 14 d&#237;as de acuerdo a las condiciones de Cancelaci&#243;n, Devoluci&#243;n y Reembolso, la tasa de tramitaci&#243;n puede ser reembolsable si cumple con las condiciones se&#241;aladas en la Pol&#237;tica de Devoluciones y previa autorizaci&#243;n de ValueBasket.com antes de la devoluci&#243;n del producto. Ninguno de los t&#233;rminos y condiciones contenidos en la confirmaci&#243;n de pago, de su orden de compra o de otro documento formar&#225;n parte del contrato.
			<br /><br />
			<strong>Pago de las compras : </strong>
			El pago de los art&#237;culos solicitados se efectuar&#225; en el momento en que se realiza el pedido. ValueBasket.com ofrece diferentes m&#233;todos de pago tales como tarjetas de cr&#233;dito y otras formas de pago m&#225;s populares para que los clientes puedan llevar a cabo sus pedidos a través de formas de pago seguras. ValueBasket.com no almacena ninguna información bancaria o información referente a tarjetas de crédito. En caso de que surja algún problema respecto al pago con su tarjeta de débito o crédito, contacte por favor con la plataforma de pago por la cual hizo el pago o con el servicio de asistencia de su tarjeta de crédito. Usted ser&#225; responsable de pagar todos los costos y cargos derivados de la compra en relaci&#243;n con el uso del m&#233;todo de pago que prefiera. Valuebasket.com no será responsable de ningún coste de emisión de transferencia o costes relacionados con el pago por tarjeta de crédito o débito. En caso de cualquier transacci&#243;n no autorizada realizada contra su cuenta por una tercera persona, usted ser&#225; el responsable &#250;ltimo de los importes facturados. Cuando el pago de su compra(s) en nuestro portal web haya sido procesado por ValueBasket.com, usted se compromete satisfacer el pago por requerimiento de ValueBasket.com.
			<br /><br />
			<strong>Aceptaci&#243;n y envío del pedido : </strong>
			Realizar un pedido con o hacer un pago a ValueBasket.com representa su oferta hacia nosotros para hacer una compra de los art&#237;culos solicitados. ValueBasket.com le enviar&#225; una respuesta a su oferta para confirmar los detalles de su orden. La oferta de compra ser&#225; aceptada por ValueBasket.com cuando sus art&#237;culos sean despachados y le enviemos el e-mail de expedici&#243;n que confirma el env&#237;o. En el caso de que su pedido incluya varios art&#237;culos, cualquier art&#237;culo (s) incluido en su oferta de compra que no haya sido despachado y por tanto no est&#233; incluido en el e-mail de expedici&#243;n, no ser&#225; incluido en la aceptaci&#243;n de su oferta de compra. Cuando su pedido incluya al menos dos artículos, ValueBasket.com podrá dividir dicho pedido de tal forma que uno o varios productos sean enviados primero y otro u otros después, con el fin de agilizar la entrega del primero o primeros. 
			<br /><br />
			<strong>Reservar ahora : </strong>
			Por norma general, cuando su cesta de pedido incluya art&#237;culos "en stock" junto con art&#237;culos en estado "reservado", los art&#237;culos "en stock" ser&#225;n enviados tan pronto como el resto de art&#237;culos en estado "reservado" est&#233;n disponibles para su expedici&#243;n.
			<br /><br />
			<strong>Transferencia de riesgo : </strong>
			Todos los art&#237;culos comprados y pagados a ValueBasket.com est&#225;n ligados a un contrato de env&#237;o. Esto significa que el riesgo de p&#233;rdida y titularidad de los art&#237;culos pasan al cliente en el momento de entrega al transportista seleccionado por ValueBasket.com. Por norma general, si usted cumple con las condiciones de reembolso y devoluci&#243;n de art&#237;culos ValueBasket.com no ser&#225; responsable de la titularidad de los art&#237;culos hasta que sean recibidos en la direcci&#243;n de devoluciones indicada previa autorizaci&#243;n junto con el formulario RMA cumplimentado. A requerimiento de ValueBasket.com el reembolso puede ser realizado sin necesidad de devoluci&#243;n del art&#237;culo, en tales circunstancias ValueBasket.com no tendr&#225; la titularidad del art&#237;culo devuelto.
			<br /><br />
			<strong>Cancelaciones, devoluciones y reembolsos : </strong>
			Puede presentar la solicitud de cancelaci&#243;n de su pedido por correo electr&#243;nico en cualquier momento antes de la expedici&#243;n. Si el env&#237;o ha sido realizado, puede solicitar el reembolso hasta 14 d&#237;as despu&#233;s de la recepci&#243;n del pedido (a no ser que su pedido haya sufrido alg&#250;n da&#241;o f&#237;sico visible a la entrega, en dicho caso deber&#225; notificarlo inmediatamente), para presentar la solicitud, simplemente env&#237;enos un correo electr&#243;nico para iniciar el proceso. Si usted cumple con las condiciones de reembolso, Valuebasket.com le proporcionar&#225; la autorizaci&#243;n y una direcci&#243;n de recogida. La mayor&#237;a de las solicitudes recibidas dentro del per&#237;odo de 14 d&#237;as y que son: (i) productos sin abrir o (ii) art&#237;culos defectuosos ser&#225;n susceptibles de reembolso. Los art&#237;culos devueltos para reembolso deben estar en su estado original con todo el embalaje original, accesorios y materiales incluidos. Art&#237;culos tales como software, bienes de consumo o los art&#237;culos afectados por la higiene, no ser&#225;n susceptibles de reembolso. Usted se compromete a asumir los costes de devoluci&#243;n del art&#237;culo (s). Los costes derivados de la devoluci&#243;n del art&#237;culo (s) pueden ser susceptibles de reembolso si se descubre que el art&#237;culo (s) se encuentra en un estado defectuoso y bajo previa autorizaci&#243;n de ValueBasket.com antes de la devoluci&#243;n del art&#237;culo (s).
			<br /><br />
			Cuando se solicita un reembolso y cumple con los requisitos para ser elegible de acuerdo con estas Condiciones de Uso, procederemos con el reembolso tan pronto como sea posible. En cualquier caso, una vez el reembolso haya sido aceptado, éste puede tardar hasta 30 (treinta) días en ser visible en su cuenta bancaria.
			<br /><br />
			<strong>Garant&#237;a del producto : </strong>
			Todos los productos, salvo menci&#243;n contraria en la descripci&#243;n de producto, cuentan con una garant&#237;a de 12 meses proporcionada por ValueBasket.com. Cualquier accesorio incluido con el producto, tales como bater&#237;as, protectores de pantalla, cables, etc, tienen una garant&#237;a est&#225;ndar de 12 meses de duraci&#243;n. Cuando el fabricante proporciona garant&#237;a junto con el producto, la garant&#237;a del fabricante sustituir&#225; la garant&#237;a de ValueBasket.com. La prueba de compra debe incluirse como una pre-condici&#243;n para tener derecho a una reparaci&#243;n bajo garant&#237;a. Cuando se encuentre alg&#250;n problema en el producto despu&#233;s de 14 d&#237;as desde la entrega y dentro del per&#237;odo de garant&#237;a, puede presentar una solicitud a su proveedor de garant&#237;a para la autorizaci&#243;n de una reparaci&#243;n, reemplazo o reembolso (a decidir por el proveedor de la garant&#237;a) para su producto. Para comenzar el proceso de solicitud de elegibilidad y autorizaci&#243;n, simplemente p&#243;ngase en contacto con nosotros <a href="[base_url;noerr;]contact">aqu&#237;</a>; ValueBasket.com le proporcionar&#225; informaci&#243;n sobre el proceso. Los problemas debidos a accidentes, negligencia o mal uso, no ser&#225;n susceptibles de inclusi&#243;n en garant&#237;a. Cuando se confirme que el problema se trata de un defecto de fabricaci&#243;n estar&#225; cubierto por la garant&#237;a, en ese caso ValueBasket.com se encargar&#225; de la reparaci&#243;n de su producto y reenv&#237;o a su domicilio sin coste alguno.
			<br /><br />
			<strong>Exclusi&#243;n de garant&#237;as y limitaci&#243;n de responsabilidad : </strong>
			Este portal web y toda la informaci&#243;n: CONTENIDO, MATERIALES, PRODUCTOS (INCLUYENDO SOFTWARE) Y LOS SERVICIOS INCLUIDOS O PUESTOS A DISPOSICI&#211;N A TRAV&#201;S DE ESTE SITIO WEB SE OFRECEN POR VALUEBASTKET.COM  &quot;TAL CUAL &quot; Y &quot;SEG&#218;N DISPONIBILIDAD &quot; SALVO QUE SE INDIQUE LO CONTRARIO POR ESCRITO. VALUEBASKET.COM NO HACE NINGUNA REPRESENTACI&#211;N O GARANT&#205;A DE NING&#218;N TIPO, EN CUANTO A LA OPERACI&#211;N DE ESTE SITIO O LA INFORMACI&#211;N, CONTENIDA, MATERIALES, PRODUCTOS (INCLUYENDO SOFTWARE) O SERVICIOS INCLUIDOS EN O PUESTOS A DISPOSICI&#211;N A TRAV&#201;S DE ESTE SITIO WEB, A MENOS QUE SE INDIQUE LO CONTRARIO POR ESCRITO.
			<br /><br />
			ValueBasket.com, su personal, objetivos y sus afiliados no ser&#225; responsables de los da&#241;os, reclamaciones, p&#233;rdidas, costes o gastos de cualquier naturaleza derivados del uso de este portal web o cualquier otro medio de comunicaci&#243;n con ValueBasket.com, o de cualquier informaci&#243;n, contenido, materiales, productos, (incluido el software) o servicios incluidos en o puesto a disposici&#243;n a trav&#233;s de este portal web.
			<br /><br />
			Usted acepta expresamente que el uso de este portal web es bajo su propio riesgo.
			<br /><br />
			<strong>Conflictos : </strong>
			Cualquier conflicto o reclamaci&#243;n relacionada con la navegaci&#243;n en nuestro portal web o de los productos y servicios vendidos o distribuidos por ValueBasket.com estar&#225; sujeta a arbitraje confidencial y obligatorio en Hong Kong en lugar de en los tribunales. El arbitraje no incluir&#225; ning&#250;n juez o jurado y la revisi&#243;n judicial del arbitraje ser&#225; limitada. Sin embargo, un &#225;rbitro puede conceder de forma individual los mismos da&#241;os y socorro que un tribunal (incluyendo medidas cautelares y declaratorias o da&#241;os estatutarios), y debe cumplir con los t&#233;rminos de estas Condiciones de Uso como lo har&#237;a un tribunal. Tanto el arbitraje  como la presentaci&#243;n de documentos se har&#225;n en ingl&#233;s (o bien acompa&#241;ado de una traducci&#243;n en ingl&#233;s de los documentos). El laudo arbitral ser&#225; el motivo en que se basa la concesi&#243;n.
			<br /><br />
			<strong>Ley aplicable : </strong>
			Usted acepta que las leyes de Hong Kong regir&#225;n estas Condiciones de Uso, las pol&#237;ticas aplicables y cualquier disputa de cualquier clase que pudiera presentarse entre usted y ValueBasket.com o sus filiales.
			<br /><br />
			<strong>Pol&#237;tica y divisibilidad : </strong>
			Por favor, revise todas las pol&#237;ticas de ValueBasket.com publicadas en este portal. Estas pol&#237;ticas tambi&#233;n gobiernan su visita a ValueBasket.com, por lo tanto, se considerar&#225; que est&#225; de acuerdo en aceptar y regirse dichas pol&#237;ticas. Estas Condiciones de Uso y Pol&#237;tica de Privacidad constituyen las condiciones completas de uso y reemplazan cualquier otra condici&#243;n, acuerdos o entendimientos (orales o escritos) entre ValueBasket.com y usted con respecto a su objeto. Si alguna de estas condiciones se considerara inv&#225;lida, nula o por cualquier raz&#243;n inaplicable, esta condici&#243;n se considerar&#225; separable y no afectar&#225; la validez y aplicabilidad de ninguna condici&#243;n restante. Si decide dejar el portal web ValueBasket.com trav&#233;s de enlaces a otras p&#225;ginas web, ValueBasket.com ser&#225; responsable de las pol&#237;ticas de privacidad de estas webs ni de las cookies que esos portales web puedan utilizar.
			<br /><br />
			<strong>Transferencia : </strong>
			Usted acepta estas Condiciones de Uso y todos los acuerdos e informaci&#243;n incorporados en este documento pueden ser transferidos autom&#225;ticamente por ValueBasket.com a un tercero. Usted no puede ceder sus obligaciones a un tercero.
			<br /><br />
			<strong>Modificaci&#243;n : </strong>
			ValueBasket.com se reserva el derecho de realizar modificaciones de su portal web, pol&#237;ticas y Condiciones de Uso en cualquier momento. Usted se compromete a aceptar y cumplir nuestras Condiciones de Uso las cuales incluyen las diferentes pol&#237;ticas publicadas en este portal web, por el hecho de acceder o hacer compras en ValueBasket.com.
			<br /><br />
			<strong>Registro de empresa : </strong>
			Sede social de ValueBasket.com<br>
			<table>
				<col width="20px"><col width="100px"><col>
				<tr>
					<td></td>
					<td>Hong Kong</td>
					<td>Unit 1505, 15/F, Yu Sung Boon Building, 107-111 Des Voeux Road Central</td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			</table>
			<br /><br />
			El portal web de ValueBasket.com se encuentra en <a href="[base_url;noerr;]">www.ValueBasket.com</a>.
			<br /><br />
		</p>
	</div>
</div>