<div id="content">
	<h5 class="side_title">Conditions d'utilisation</h5>

	<div class="text silver_box static_page">
		<p>
			Derni&#232;re mise &#224; jour: le 23 septembre 2013
			<br /><br /><br />
			<strong>Introduction : </strong>
			ValueBasket.com Limited (ValueBasket.com) vous fournit les fonctionnalit&#233;s de son site internet soumis aux conditions suivantes. S'il vous plait lisez attentivement notre site Web. En visitant ou en achetant chez ValueBasket.com, vous vous engagez &#224; accepter et &#224; &#234;tre li&#233; par ces conditions, qui comprennent les autres politiques affich&#233;es sur ce site, tels que modifi&#233;s de temps &#224; autre.
			<br /><br />
			<strong>Confidentialit&#233; : </strong>
			S'il vous pla&#238;t consulter notre <a href="[base_url;noerr;]privacy_policy">Politique de confidentialit&#233;</a> pour nos pratiques applicables lorsque vous utilisez notre site Web.
			<br /><br />
			<strong>Copyright : </strong>
			Tout le contenu de notre site Web (y compris les textes, graphiques, logos, ic&#244;nes, images, clips audio, t&#233;l&#233;chargements num&#233;riques, compilations de donn&#233;es et logiciels) et la compilation de tout le contenu de telle sorte qu'utilis&#233; sur ce site est la propri&#233;t&#233; de ValueBasket.com ou de ses fournisseurs de contenu, et est prot&#233;g&#233; par les lois de copyright applicables.
			<br /><br />
			<strong>Marque Commerciale : </strong>
			ValueBasket.com est notre marque commerciale et ne peut &#234;tre utilis&#233;e en liaison avec tout autre produit ou service qui n'appartient pas &#224; ValueBasket.com ou qui peut causer la confusion des clients ou de quelque mani&#232;re d&#233;nigrer ou discr&#233;diter ValueBasket.com. Les m&#234;mes restrictions s'appliquent &#224; l'utilisation d'autres marques, qui n'appartiennent pas &#224; ValueBasket.com, qui apparaissent sur notre site Web, mais qui sont la propri&#233;t&#233; de leurs propri&#233;taires respectifs, qui peuvent ou peuvent ne pas &#234;tre connect&#233;s &#224; ValueBasket.com.
			<br /><br />
			<strong>Communications &#233;lectroniques : </strong>
			Lorsque vous visitez ou envoyer des e-mails &#224; ValueBasket.com, vous communiquez avec ValueBasket.com par voie &#233;lectronique. Vous consentez &#224; recevoir des communications de ValueBasket.com par voie &#233;lectronique. ValueBasket.com communiquera avec vous par e-mail ou en publiant des avis sur le site ValueBasket.com. Vous acceptez que toutes les conditions, les accords, avis, informations et autres communications qui vous sont fournis par voie &#233;lectronique satisfont &#224; toute exigence que les communications soient faites par &#233;crit.
			<br /><br />
			<strong>Licence d'utilisation et acc&#232;s au site : </strong>
			ValueBasket.com accorde une licence limit&#233;e pour acc&#233;der et faire usage personnel de ce site et interdit tout t&#233;l&#233;chargement (sauf pour la page en cache) ou de la modification de tout ou partie de celui-ci, sauf avec le consentement expr&#232;s pr&#233;alable et &#233;crit de ValueBasket.com. Cette licence ne comprend pas toute collecte, utilisation, revente ou utilisation commerciale de ce site ou le contenu du site, toute utilisation d&#233;riv&#233;e de ce site ou son contenu, tout t&#233;l&#233;chargement ou copie des informations de compte pour le b&#233;n&#233;fice d'une autre personne, ou toute utilisation de toute collecte de donn&#233;es et des outils d'extraction. Ce site, tout ou
partie, ne peut &#234;tre reproduit, dupliqu&#233;, copi&#233;, vendu, revendu, visit&#233;, ou exploit&#233; &#224; des fins commerciales sans le consentement expr&#232;s pr&#233;alable et &#233;crit de ValueBasket.com. Vous ne pouvez pas encadrer ou utiliser des techniques de cadrage pour joindre une marque commerciale, un logo ou autre information exclusive (y compris les images, textes, mise en page, ou forme) de ValueBasket.com sans l'autorisation &#233;crite expresse de ValueBasket.com. Vous ne pouvez utiliser aucun meta tags ou tout autre &#xab;texte cach&#233;&#xbb; qui peut faire r&#233;f&#233;rence au nom ou &#224; la marque ValueBasket.com &#x2122; sans l'autorisation &#233;crite expresse de ValueBasket.com. Toute utilisation non autoris&#233;e met fin &#224; la licence accord&#233;e par ValueBasket.com pour l'utilisation du site. Vous disposez d'un droit limit&#233;, r&#233;vocable et non exclusif de cr&#233;er et de maintenir un lien hypertexte vers la page d'accueil de ValueBasket.com &#224; condition que ce lien ne pr&#233;sente pas ValueBasket.com, ses produits ou services de mani&#232;re fausse, trompeuse, d&#233;rogatoire, ou de tout autre mani&#232;re offensive. Vous ne pouvez pas utiliser le logo ValueBasket.com ou tout autre graphisme ou marque dans le cadre de la liaison sans l'autorisation expresse &#233;crite de ValueBasket.com.
			<br /><br />
			<strong>Application de la loi : </strong>
			ValueBasket.com se r&#233;serve le droit d'enqu&#234;ter et poursuivre les violations de n'importe quelle partie des Conditions d'utilisation dans toute la mesure de la loi; ce faisant, ValueBasket.com peut impliquer et coop&#233;rer avec les autorit&#233;s r&#233;pressives pour poursuivre les utilisateurs. Vous reconnaissez que ValueBasket.com n'a aucune obligation de surveiller votre acc&#232;s &#224;, ou l'utilisation du site ValueBasket.com, mais se r&#233;serve le droit de le faire &#224; des fins d'exploitation du site web ValueBasket.com, afin d'assurer votre conformit&#233; avec les Conditions d'utilisation ou de se conformer &#224; la loi applicable ou l'ordre ou l'exigence d'un tribunal, un organisme administratif ou un autre organisme gouvernemental.
			<br /><br />
			<strong>Votre compte : </strong>
			Vous ne pouvez utiliser ValueBasket.com que si vous &#234;tes un adulte, et en utilisant le site ValueBasket.com, vous d&#233;clarez et garantissez que vous avez 18 ans ou plus. Si vous &#234;tes ag&#233; de moins de 18 ans, vous ne pouvez pas utiliser, acc&#233;der ou vous inscrire sur ValueBasket.com. En utilisant ce site, ValueBasket.com vous oblige &#224; vous inscrire et cr&#233;er un compte sur le site. Vous vous engagez en tant que condition d'utilisation et l'enregistrement que nous puissions vous contacter pour vous informer des modifications apport&#233;es &#224; ces Conditions d'utilisation ou de d&#233;crire de nouveaux services disponibles &#224; partir de ValueBasket.com.
			<br /><br />
			Vous &#234;tes responsable du maintien de la confidentialit&#233; de toutes les activit&#233;s qui se produisent sous votre compte et mot de passe. Vous pouvez &#233;galement accepter la responsabilit&#233; de restreindre l'acc&#232;s &#224; votre ordinateur, et vous vous engagez &#224; informer imm&#233;diatement ValueBasket.com de toute violation de la s&#233;curit&#233; de votre compte. ValueBasket.com ne sera pas responsable de toute perte d&#233;coulant de l'utilisation non autoris&#233;e de votre compte.
			<br /><br />
			ValueBasket.com se r&#233;serve le droit de refuser le service, fermer les comptes, de supprimer ou &#233;diter du contenu, ou annuler des commandes &#224; la discr&#233;tion absolue de ValueBasket.com sans fournir de motif. Vous pouvez annuler votre compte &#224; tout moment via les informations disponibles sur notre page <a href="[base_url;noerr;]contact">Contactez-nous</a>.
			<br /><br />
			<strong>Descriptions du produit : </strong>
			ValueBasket.com fait tous les efforts pour rendre nos descriptions de produits aussi pr&#233;cises que possible. Toutefois, ValueBasket.com ne garantit pas que la description des produits ou tout autre contenu disponible sur le site sont exacts, complets, fiables, &#xe0; jour ou sans erreur. Si vous recevez un produit de ValueBasket.com qui n'est pas comme d&#233;crit, votre seul recours est de le renvoyer dans un &#233;tat inutilis&#233;; en conformit&#xe9; avec notre condition sur Annulation, Retours et remboursements.
			<br /><br />
			<strong>Prix : </strong>
			ValueBasket.com ne peut pas confirmer le prix d'un article avant que vous passiez votre commande. Bien que ValueBasket.com fasse tous les efforts pour rendre nos prix aussi pr&#233;cis que possible, certains objets trouv&#233;s r&#233;pertori&#233;s sur notre site Web peuvent &#234;tre erron&#233;s si le prix exact d'un article est en fait plus &#233;lev&#233; que le prix command&#233; ValueBasket.com, &#224; sa propre discr&#233;tion, vous contactera pour plus de d&#233;tails avant l'exp&#233;dition ou annulera votre commande et vous informera de cette annulation.
			<br /><br />
			<strong>Passation de commande et d'importation : </strong>
			En passant commande chezValueBasket.com, vous assumez l'enti&#232;re responsabilit&#233; de veiller &#224; ce que votre achat peut &#234;tre import&#233; en conformit&#233; avec les lois du pays dans lequel vous avez demand&#233; &#224; ValueBasket.com d'exp&#233;dier votre achat et vous convenez &#233;galement que vous &#234;tes le seul importateur pour l'achat de votre produit &#224; toutes fins, y compris mais non limit&#233; &#224; la r&#232;glementation douani&#232;re, droits d'auteur et droit des marques et vous vous engagez &#224; respecter toutes les lois et r&#232;glements du pays dans lequel les marchandises sont re&#231;ues. A cette fin, vous reconnaissez et acceptez que le r&#244;le de ValueBasket.com est limit&#233; &#224; vous procurer vos produits achet&#233;s &#224; Hong Kong et autres r&#233;gions, et de mettre ces produits &#224; votre disposition sur le site pour l'achat &#224; Hong Kong et pour l'importation dans votre pays. En aucun cas, ValueBasket.com ne sera partie &#224; l'importation de ces produits ni ne pourra &#234;tre responsable de toute responsabilit&#233; d&#233;coulant de l'application des lois de tout pays autre que Hong Kong pour l'importation et la vente de produits disponibles sur le site, y compris et sans limite, la r&#232;glementation douani&#232;re et les saisies douni&#232;res, les d&#233;tentions et les saisies et les lois sur le copyright et les marques. Les clients en dehors de Hong Kong autorisent ValueBasket.com &#224; prendre des dispositions pour le d&#232;douanement en leur nom pour les achats effectu&#233;s. Les proc&#232;dures de d&#232;douanement peuvent mandater l'ouverture et l'inspection des livraisons transfrontali&#232;res.
			<br /><br />
			<strong>Importation, taxes et frais : </strong>
			Lorsque les droits et taxes d'importation (directement et indirectement li&#233;s) sont applicables sur les livraisons &#224; l'&#233;tranger en dehors de Hong Kong, ils seront normalement soumis &#224; l'acqu&#233;reur; imp&#244;ts directement li&#233;s et droits comprennant les taxes &#224; l'importation ou taxes qui sont pr&#233;lev&#233;es sur les factures, tout frais de manutention du transporteur, surtaxes douani&#232;res et les surtaxes de transfert &#224; domicile per&#231;us par le transporteur, les taxes indirectement li&#233;es et droits d&#233;coulant de politiques douani&#232;res diff&#233;rentes &#224; travers le monde qui peuvent appliquer d'autres droits de douane ou des frais suppl&#233;mentaires de d&#233;douanement. Les politiques douani&#232;res diff&#232;rent dans chaque pays, par cons&#233;quent, vous devriez communiquer avec votre bureau de douanes local pour tout renseignements suppl&#233;mentaires relatifs aux politiques applicables. ValueBasket.com n'a aucun contr&#244;le sur ces droits &#224; l'importation ou taxes. Pour certains &#233;l&#233;ments et combinaisons de livraison &#224; destination des pays, des frais de manutention et importation pris en charge par ValueBasket.com peuvent &#234;tre inclus et anot&#233;s sur votre facture d'exp&#233;dition. Lorsqu'une taxe de traitement des importations est inclus, ValueBasket.com portera la responsabilit&#233; pour les taxes et droits qui ne sont directement li&#233;s &#224; l'ordre factur&#233;. Toute taxe d'importation inclus sur votre avis d'exp&#233;dition est non-remboursable. Si vous retournez votre produit dans les 14 jours suivant l'achat, conform&#233;ment &#224; notre condition sur Annulations, retours et les remboursements, les frais de manutention &#224; l'importation peuvent &#234;tre rembours&#233;s &#224; condition que vous soyez admissible au titre de la politique de retour et que vous obtenez l'autorisation pr&#233;alable de ValueBasket. com avant le retour du produit. Aucun termes et conditions figurant dans la confirmation de votre paiement ou de votre ordre d'achat ou autre document de l'acheteur fera partie du contrat.
			<br /><br />
			<strong>Paiement des achats : </strong>
			Le paiement pour les articles command&#233;s est due au moment ou la commande est reconnue. ValueBasket.com offre, &#224; la caisse, diverses m&#233;thodes de paiement comme les cartes de cr&#233;dit et d'autres m&#233;thodes de paiement populaires pour que les clients puisse effectuer le paiement de leurs articles command&#233;s. Vous accepter la responsabilit&#233; de payer tous les frais et honoraires dans le cadre de vos articles command&#233;s en ce qui concerne l'utilisation de la m&#233;thode de paiement de votre choix. Dans le cas de toutes les transactions non autoris&#233;es effectu&#233;es sur votre compte de paiement par un tiers, vous serez responsable pour les montants factur&#233;s. Lorsque le paiement pour l'achat (s) sur notre site web n'est pas r&#233;gl&#233; &#224; ValueBasket.com, vous acceptez de payer tous les montants dus &#224; ValueBasket.com sur demande.
			<br /><br />
			<strong>Acceptation d'une commande : </strong>
			Passer une commande, effectuer un paiement &#224; ValueBasket.com repr&#233;sente votre demande d'effectuer l'achat des articles command&#233;s. ValueBasket.com vous enverra confirmation de votre offre pour confirmer vos d&#233;tails de la commande. L'offre de votre achat sera accept&#233;e par ValueBasket.com lorsque nous vous exp&#233;dions le produit et envoyons un e-mail d'exp&#233;dition en confirmation de cela. Dans le cas o&#249;? votre commande comprend plusieurs &#233;l&#233;ments, tout &#233;l&#233;ment (s) inclus dans votre offre d'achat qui ne sont pas exp&#233;di&#233;s et non inclus dans l'e-mail d'exp&#233;dition, ne sera pas inclus dans l'acceptation de votre offre d'achat pour les articles concern&#233;s.
			<br /><br />
			<strong>Pr&#233;-commandes : </strong>
			Lorsque votre panier d'achat est compos&#233; d'articles &#171; en stock &#187; ainsi que d'articles en &#171; pr&#233;-commande &#187;, les articles &#171; en stock &#187; seront exp&#233;di&#233;s d&#232;s lors que les articles en &#171; pr&#233;-commande &#187; sont aussi disponibles pour exp&#233;dition.
			<br /><br />
			<strong>Passage du risque : </strong>
			Tous les articles achet&#233;s &#224; partir de, et dont le paiement est fait &#224; ValueBasket.com sont soumis conform&#233;ment &#224; un contrat d'exp&#233;dition. Cela signifie que le risque de perte et le titre de ces articles vous incombe &#224; la livraison au transporteur choisi par ValueBasket.com de livrer votre commande. Lorsque vous &#234;tes admissible &#224; un remboursement pour l'article retourn&#233; (s), ValueBasket.com ne prend pas le titre de l'article retourn&#233; (s) jusqu'&#224; ce que l'&#233;l&#233;ment (s) arrive &#224; notre adresse de retour prescrite avec l'autorisation appropri&#233;e et le formulaire d&#251;ment rempli. &#224; la discr&#233;tion de ValueBasket.com, un remboursement peut &#234;tre d&#233;livr&#233; sans n&#233;cessiter un retour; dans de telles circonstances, ValueBasket.com ne prend pas le titre de l'article rembours&#233;.
			<br /><br />
			<strong> Division de commande : </strong>
			Valuebasket se réserve le droit de diviser votre commande lorsque plusieurs articles sont achetés au cours d'une même commande afin d'assurer une livraison plus rapide. Valuebasket vous informera de cette division afin de vous confirmer vos informations d'expédition. Les modifications apparaitront alors sur la page Mon Compte, avec un rappel des articles devant être expédiés dès que possible.
			<br /><br />
			<strong>Annulation, Retours et Remboursements : </strong>
			Vous pouvez soumettre des demandes d'annulation de votre commande par e-mail &#224; tout moment avant l'exp&#233;dition. Lorsque l'exp&#233;dition a &#233;t&#233; faite, vous pouvez demander un remboursement jusqu'&#224; 14 jours apr&#232;s que les marchandises sont livr&#233;es (&#224; moins qu'un dommage physique soit constat&#233; lors de la livraison de votre commande, auquel cas vous devez nous informer imm&#233;diatement), pour pr&#233;senter la demande, il suffit de nous envoyer un courriel pour d&#233;marrer le processus. Lorsque vous &#234;tes admissible &#224; un remboursement, Valuebasket.com fournira une autorisation et une adresse de retour le cas &#233;ch&#233;ant. La plupart des demandes, qui sont au sein de la p&#233;riode de 14 jours et qui sont (i) pour les nouveaux articles dans leur emballage ou (ii) s'av&#232;re d&#233;fectueux seront admissibles &#224; un remboursement. Les marchandises retourn&#233;es pour remboursement doivent &#234;tre dans leur &#233;tat d'origine avec tous les emballages d'origine, accessoires et mat&#233;riel inclus. Vous devez prendre toutes les pr&#233;cautions raisonnables pour la protection des marchandises et les retourner dans leur &#233;tat d'origine et en bon &#233;tat. Lorsque les achats sont ouverts et sont des logiciels utilisables, des biens de consommation, ou des articles touch&#233;s par l'hygi&#232;ne, ces articles ne seront pas admissibles &#224; un remboursement. Vous vous engagez &#224; supporter les frais de retour de l'article (s). Les co&#251;ts engag&#233;s pour retourner l'article (s) peuvent &#234;tre admissibles &#224; un remboursement lorsque l'&#233;l&#233;ment (s) est d&#233;fectueux et si l'autorisation appropri&#233;e de ValueBasket.com est demand&#233;e et fournie avant le retour de l'article (s).
			<br /><br />
			Lorsqu’un remboursement est demandé et que l’éligibilité est confirmé en accordance à ces Conditions d’Utilisations, nous procèderons au remboursement aussitôt que possible. Dans n’importe quel cas, le remboursement peut prendre 30 (trente) jours, après que l’éligibilité du remboursement ait été confirmée, pour apparaitre sur votre compte bancaire.
			<br /><br />
			<strong>Garanties des produits : </strong>
			Tous les produits, sauf mention contraire indiqu&#233;e sur la page de description du produit, sont livr&#233;s avec une Garantie de 36 Mois fournie par ValueBasket.com; tous les accessoires pour vos produits, tels que les batteries, protecteurs d'&#233;crans, c&#226;bles, etc. sont livr&#233;s avec une Garantie standard de 12 Mois. Lorsqu'une garantie du fabricant est fournie avec votre produit, la garantie du fabricant remplace la garantie par ValueBasket.com. Une preuve d'achat doit &#234;tre fournie en tant que pr&#233;-condition d'&#233;ligibilit&#233; &#224; une r&#233;paration sous garantie. Si un d&#233;faut sur votre produit se produit 14 jours apr&#232;s  la date de livraison et &#224; l'int&#233;rieur de la p&#233;riode de garantie fournie, vous pouvez soumettre une demande &#224; votre fournisseur de garantie pour l'autorisation d'une r&#233;paration, de remplacement ou de remboursement (&#224; la discr&#233;tion absolue de votre fournisseur de garantie) pour votre produit. Pour commencer le processus de demande d'admissibilit&#233; et d'autorisation, il suffit de nous contacter <a href="[base_url;noerr;]contact">ici</a>; ValueBasket.com fournira ensuite les d&#233;tails sur la proc&#233;dure &#224; suivre. Les d&#233;fauts dus &#224; un accident, une n&#233;gligence ou une mauvaise utilisation ne sont pas admissibles &#224; l'inscription en vertu de la garantie. Lorsqu'il est confirm&#233; qu'un d&#233;faut de fabrication a eu lieu et est couvert par la garantie, ValueBasket.com fera le n&#233;cessaire pour une r&#233;paration de votre produit et vous le retournera sans frais.
			<br /><br />
			<strong>Exclusion de garanties et limitation de responsabilit&#233; : </strong>
			CE CITE WEB ET TOUTES LES INFORMATIONS, DU CONTENU, LES PRODUITS (Y COMPRIS LES LOGICIELS) ET SERVICES INCLUS SUR OU AUTREMENT RENDU DISPONIBLE PAR L'INTERMEDIAIRE DE CE SITE SONT FOURNIS PAR VALUEBASKET.COM SUR UNE &quot;TEL QUEL&quot; ET &quot; SELON LA DISPONIBILIT&#xc9; &#xbb;, SAUF INDICATION CONTRAIRE PAR &#xc9;CRIT. VALUEBASKET.COM NE FAIT AUCUNE DECLARATION OU GARANTIE DE QUELQUE NATURE QUE CE SOIT, EXPRESSE OU IMPLICITE, QUANT AU FONCTIONNEMENT DE CE SITE WEB OU DE L'INFORMATION, DU CONTENU, LES PRODUITS (Y COMPRIS LES LOGICIELS) OU SERVICES INCLUS SUR OU AUTREMENT RENDU DISPONIBLE PAR L'INTERMEDIAIRE DE CE SITE WEB, SAUF INDICATION CONTRAIRE PAR ECRIT.
			<br /><br />
			ValueBasket.com, son personnel, ses objectifs et ses filiales ne seront pas tenus responsables et ne doivent pas &#234;tre tenus responsables des dommages, r&#233;clamations, pertes, co&#251;ts ou d&#233;penses de toute nature r&#233;sultant de votre utilisation de ce site ou de tout moyen de communication avec ValueBasket. com, ou de toute information, le contenu, les mat&#233;riaux, produits, (y compris les logiciels) ou les services inclus ou autrement mis &#224; votre disposition sur ce site.
			<br /><br />
			Vous convenez express&#233;ment que votre utilisation de ce site est &#224; vos risques et p&#233;rils.
			<br /><br />
			<strong>Litiges : </strong>
			Toute contestation ou revendication ne concernant en aucune fa&#231;on votre visite sur notre site Web ou des produits ou services vendus ou distribu&#233;s par ValueBasket.com sera soumis &#224; l'arbitrage ex&#233;cutoire confidentielle &#224; Hong Kong, plut&#244;t que devant un tribunal, sauf que vous pouvez soumettre votre plainte &#224; un tribunal d'instance si vos revendications sont admissibles. L'arbitrage ne comprendra pas un juge ou un jury, et le contr&#244;le judiciaire d'une salle d'arbitrage est limit&#233;. Cependant, un arbitre peut accorder sur une base individuelle les m&#234;mes dommages et int&#233;r&#234;ts en tant que tribunal (y compris une mesure injonctive et d&#233;claratoire ou dommages-int&#233;r&#234;ts l&#233;gaux), et doit respecter les termes des pr&#233;sentes Conditions d'utilisation tel qu'un tribunal le ferait. L'arbitrage doit &#234;tre effectu&#233;, et les documents pr&#233;sent&#233;s, en anglais, ou &#234;tre accompagn&#233;s d'une traduction anglaise des documents. La sentence arbitrale doit pr&#233;ciser la raison (s) sur lesquels la sentence est fond&#233;e.
			<br /><br />
			<strong>Droit Applicable : </strong>
			Vous acceptez que les lois de Hong Kong r&#233;giront ces Conditions d'Utilisation, les autres politiques applicables et tout litige de quelque sorte qui pourrait surgir entre vous et ValueBasket.com ou de ses filiales.
			<br /><br />
			<strong>Politique et Divisibilit&#233; : </strong>
			S'il vous pla&#238;t examiner tous les politiques de ValueBasket.com affich&#233;es sur ce site. Ces politiques r&#233;gissent &#233;galement votre visite &#224; ValueBasket.com, par cons&#233;quent, vous serez consid&#233;r&#233;; comme ayant accept&#233; et d'&#234;tre li&#233; par ces politiques. Ces Conditions d'utilisation et Politique de confidentialit&#233;; constituent les Conditions d'utilisation enti&#232;res et remplacent toutes autres conditions, des accords ou arrangements (oral ou &#233;crit) entre ValueBasket.com et vous par rapport &#224; leur sujet. Si aucune de ces conditions est jug&#233;e invalide, nulle ou inapplicable pour quelque raison, la condition sera r&#233;put&#233;e divisible et n'affectera pas la validit&#233; et l'applicabilit&#233; de toute condition restante. Si vous choisissez de quitter le site ValueBasket.com via des liens vers des sites autres que ValueBasket.com, ValueBasket.com n'est pas responsable des politiques de confidentialit&#233; de ces sites ou les cookies que ces sites utilisent.
			<br /><br />
			<strong>Affectation : </strong>
			Vous convenez que ces Conditions d'utilisation et tous les accords et les informations qui y sont int&#233;gr&#233;s peuvent &#234;tre automatiquement attribu&#233;s par ValueBasket.com, &#224; sa seule discr&#233;tion, &#224; un tiers. Vous ne pouvez c&#233;der vos obligations &#224; une autre partie.
			<br /><br />
			<strong>Modification : </strong>
			ValueBasket.com se r&#233;serve le droit, &#224; sa seule discr&#233;tion, de faire des changements &#224; notre site Web, les politiques et les pr&#233;sentes Conditions d'Utilisation &#224; tout moment. Vous vous engagez &#224; accepter et &#224; &#234;tre li&#233; par nos Conditions g&#233;n&#233;rales d'utilisation, qui comprennent les diff&#233;rentes politiques affich&#233;es sur ce site, par l'acte de visite ou de shopping au ValueBasket.com.
			<br /><br />
			<strong>Registre des soci&#233;t&#233;s : </strong>
			ValueBasket.com poss&#232;de des bureaux enregistr&#233;s<br>
			<table>
				<col width="20px"><col width="100px"><col>
				<tr>
					<td></td>
					<td>Hong Kong</td>
					<td>Unit 1505, 15/F, Yu Sung Boon Building, 107-111 Des Voeux Road Central</td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			</table>
			<br /><br />
			Le site web de ValueBasket.com se trouve a <a href="[base_url;noerr;]">www.ValueBasket.com</a>.
			<br /><br />
		</p>
	</div>
</div>