<div id="content">
	<h5 class="side_title">Condizioni d'uso</h5>

	<div class="text silver_box static_page">
		<p>
			Ultimo Aggiornamento: 23 Settembre 2013
			<br /><br /><br />
			<strong>Introduzione : </strong>
			ValueBasket.com Limited (ValueBasket.com) fornisce funzionalita del sito web per voi soggetto alle seguenti condizioni. Si prega di leggere con attenzione il nostro sito web. Visitando o acquistando su ValueBasket.com, l'utente accetta di accettare e di essere vincolato da queste condizioni, che includono le altre politiche pubblicate su questo sito, come modificati di volta in volta.
			<br /><br />
			<strong>Privacy : </strong>
			Leggi le nostre <a href="[base_url;noerr;]privacy_policy">Politiche di Privacy</a> per le nostre procedure applicabili quando si utilizza il nostro sito web.
			<br /><br />
			<strong>Nota Copyright : </strong>
			Tutti i contenuti presenti sul nostro sito web (incluso il testo, grafica, loghi, icone, immagini, clip audio, download digitali, compilazioni di dati e software) e la compilazione di tutti i contenuti che viene utilizzata su questo sito e di proprieta di ValueBasket . com o dei suoi fornitori di contenuti e sono protetti dalle vigenti leggi sul copyright.
			<br /><br />
			<strong>Nota Marchi di Fabbrica : </strong>
			ValueBasket.com e il nostro marchio di fabbrica e non puo essere utilizzato in connessione con qualsiasi altro prodotto o servizio che non appartiene a ValueBasket.com o che possono causare confusione tra i clienti o in qualsiasi maniera che denigri o scredi ValueBasket.com. Le stesse restrizioni all'uso valgono per gli altri marchi, che non appartengono a ValueBasket.com, che compaiono sul nostro sito web ma che sono di propieta dei loro rispettivi proprietari, che possono o non possono essere collegati a Valuebasket.com.
			<br /><br />
			<strong>Comunicazione elettronica : </strong>
			Quando si visita o invia e-mail a ValueBasket.com, si comunica con ValueBasket.com elettronicamente. L'utente acconsente di ricevere comunicazioni da ValueBasket.com elettronicamente. ValueBasket.com comunichera con voi via e-mail o messaggi sul sito ValueBasket.com. L'utente accetta che tutte le condizioni, gli accordi, gli avvisi, informazioni e altre comunicazioni fornite a voi elettronicamente soddisfino i requisiti di tali comunicazioni in forma scritta.
			<br /><br />
			<strong>Licenza d'Uso e Acceso al Sito : </strong>
			ValueBasket.com concede una licenza limitata per accedere e fare uso personale di questo sito e vieta qualsiasi download (ad eccezione delle pagine) o della modifica di una o tutte di esso, se non con l'espresso consenso scritto di ValueBasket.com. Questa licenza non iclude qualsiasi raccolta, uso, la rivendita o l'uso commerciale di questo sito web o il contenuto del sito, qualsiasi uso derivato di questo sito o del suo contenuto, qualsiasi scaricamento o la duplicazione delle informazioni cliente a vantaggio di un'altra persona, o qualsiasi utilizzo di qualsiasi raccolta e l'estrazione di dati strumenti. Questo sito web, o parte, non puo essere riprodotto, duplicato, copiato, venduto, rivenduto, visitato, o comunque sfruttato per scopi commerciali senza il previo consenso scritto di ValueBasket.com. L'utente non puo utilizzare frame o tecniche di framing per includere marchi, loghi o altre informazioni proprietarie (comprese immagini, testi, layout di pagina, o forma) di ValueBasket.com senza l'espresso consenso scritto ValueBasket.com. L'utente non puo utilizzare alcun meta tag o altro che possa avere riferimento al nome o ai marchi ValueBasket.com s 'senza l'espresso consenso scritto di ValueBasket.com. Qualsiasi utilizzo non autorizzato termina la licenza concessa da ValueBasket.com per \ \ l'utilizzo del sito web. Viene concesso il diritto limitato, revocabile e non esclusivo di creare e mantenere un collegamento ipertestuale alla home page di ValueBasket.com solo quando questo link non ritragga ValueBasket.com, o dei suoi prodotti o servizi in modo falso, ingannevole, spregiativo o questione altrimenti offensivo. L'utente non puo utilizzare il logo ValueBasket.com o altro grafico proprietario o un marchio come parte del collegamento senza l'espressa autorizzazione scritta di ValueBasket.com.
			<br /><br />
			<strong>Applicazione delle condizioni : </strong>
			ValueBasket.com si riserva il diritto di indagare e perseguire le violazioni di qualsiasi parte delle Condizioni di Utilizzo, nella misura massima consentita dalla legge, in tal modo, ValueBasket.com puo coinvolgere e cooperare con le forze dell'ordine nel perseguire gli utenti. L'utente riconosce che ValueBasket.com ha l'obbligo di monitorare l'accesso o l'uso del sito web ValueBasket.com, ma si riserva il diritto di farlo per il fine di operare sul sito web ValueBasket.com, per garantire la conformita con le condizioni di utilizzo o di rispettare il diritto applicabile o l'ordine o la richiesta di un tribunale, ente amministrativo o di altro ente governativo.
			<br /><br />
			<strong>Il tuo Profilo : </strong>
			E possibile utilizzare ValueBasket.com solo se sei un adulto, e utilizzando il sito ValueBasket.com, l'utente garantisce e dichiara di avere 18 anni di eta o piu. Se hai meno di 18 anni, non utilizzare, accedere o registrarsi sul ValueBasket.com. Nel utilizzo di questo sito, ValueBasket.com richiede di registrarsi e creare un account sul sito. L'utente accetta come condizione d'uso e di registrazione che possiamo contattarvi per informarvi di modifiche alle presenti Condizioni di Utilizzo o descrivere nuovi servizi disponibili da ValueBasket.com.
			<br /><br />
			L'utente e responsabile di mantenere la riservatezza di tutte le attivita che avvengono sul suo account e la password. Si accetta anche la responsabilita di limitare l'accesso al tuo computer, e si impegna a comunicare immediatamente ValueBasket.com di qualsiasi violazione della sicurezza del tuo account. ValueBasket.com non sara responsabile per eventuali danni derivanti da un utilizzo non autorizzato del proprio account.
			<br /><br />
			ValueBasket.com si riserva il diritto di rifiutare il servizio, chiudere i conti, rimuovere o modificare il contenuto, o annullare ordini a ValueBasket.com discrezione assoluta di dare alcuna motivazione. Puoi cancellare il tuo account in qualsiasi momento tramite le informazioni trovate sula nostra <a href="[base_url;noerr;]contact">Contattaci</a> pagina.
			<br /><br />
			<strong>Descrizione dei prodotti : </strong>
			ValueBasket.com fa ogni sforzo per rendere le nostre descrizioni dei prodotti il piu preciso possibile. Tuttavia, ValueBasket.com non garantisce che la descrizione dei prodotti o altri contenuti disponibili sul sito siano accurate, complete, affidabili, aggiornati o privi di errori. Se si riceve un prodotto da ValueBasket.com che non e come descritto, l'unico rimedio e restituirli nella condizione di inutilizzato in conformita con la nostra condizione di annullamento, Restituzioni e Rimborsi.
			<br /><br />
			<strong>Prezzi : </strong>
			ValueBasket.com non puo confermare il prezzo di un articolo fino a quando si effettua l'ordine. Mentre ValueBasket.com fa ogni sforzo per rendere i nostri prezzi il piu preciso possibile, alcune voci trovate elencato sul nostro sito possono essere correttamente valutate, se il prezzo corretto per un elemento e in realta superiore al vostro prezzo ordinato, ValueBasket.com provvedera, a nostra discrezione, o contattare per ulteriori dettagli prima della spedizione o annullare l'ordine e notifica di tale annullamento.
			<br /><br />
			<strong>Piazzamento dell'ordine e Importazione : </strong>
			Effettuando un ordine con ValueBasket.com, si assume ogni responsabilita per il garantire che il tuo acquisto  possono essere importati in conformita con le leggi del paese per cui e stato richiesto ValueBasket.com per spedire il vostro acquisto e anche d'accordo che tu sei l'unico importatore per l'acquisto del prodotto a tutti gli effetti, incluso ma non limitato ai regolamenti doganali , le leggi sul copyright e sui marchi e si impegna a rispettare tutte le leggi ei regolamenti del paese in cui le merci sono ricevute. A tal fine, l'utente riconosce e accetta che il ruolo ValueBasket.com si limita a procurare i vostri prodotti acquistati a Hong Kong e in altre regioni, e rendere questi prodotti disponibili attraverso il sito web per voi per l'acquisto a Hong Kong e per la vostra importazione al vostro paese. In nessun caso ValueBasket.com essere partito per l'importazione di tali prodotti ne ValueBasket.com essere responsabile per qualsiasi responsabilita derivante secondo le leggi di un paese diverso da Hong Kong per l'importazione e la vendita dei prodotti disponibili sul sito,comprese leggi doganali, copiright, marchi di fabbrica e relative normative a riguardo.I clienti al di fuori di Hong Kong autorizzano ValueBasket.com di prendere accordi per le operazioni doganali per loro conto per gli acquisti effettuati. Operazioni di sdoganamento possono affidare l'apertura e l'ispezione delle consegne transfrontaliere .
			<br /><br />
			<strong>Doganali, le imposte e tasse : </strong>
			Dove (direttamente e indirettamente collegate) sono applicabili sulle consegne all'estero al di fuori di Hong Kong dazi e delle tasse, questi saranno normalmente sottoposti al destinatario; imposte e tasse direttamente connesse comprendono quelle tasse di importazione / doveri che gravano sul fine fattura, di ogni corriere gestione pagamento ed eventuali supplementi di inoltro Domicilio riscosse dal corriere; imposte e tasse indirettamente correlati derivano da diverse politiche doganali di tutto il mondo che possono applicarsi altri supplementi doganali o costi di liquidazione. Le politiche doganali variano in ogni paese, quindi, e necessario contattare l'ufficio doganale locale per ulteriori domande relative alle politiche applicabili. ValueBasket.com non ha alcun controllo su questi dazi o delle tasse. Per alcuni articoli e alcuni paesi di destinazione di consegna, puo essere inclusa una commissione di gestione di importazione a carico ValueBasket.com e annotata sulla fattura della spedizione.Dove e inclusa una commissione di gestione di importazione, ValueBasket.com si assume la responsabilita per le imposte e tasse che sono solo direttamente legati all'ordine fatturato. Qualsiasi commissione di gestione di importazione incluso sul vostro avviso della spedizione non e rimborsabile. Se si restituisce il prodotto entro 14 giorni dalla data di acquisto in conformita con la nostra condizione di disdette, i ritorni e rimborsi, la commissione di gestione di importazione puo essere rimborsato a condizione che siete eleggibile per titolo della politica Returns e che si ottiene previa autorizzazione ValueBasket.com prima del ritorno del prodotto. Nessun termini e le condizioni contenute nella conferma del pagamento o del vostro ordine d'acquisto o altro documento dell'acquirente faranno parte del contratto.
			<br /><br />
			<strong>Ordini divisi : </strong>
			ValueBasket si riserva il diritto di dividere il tuo ordine in misura preventiva laddove un ordine comprenda più di un articolo, per offrire tempi di consegna più rapidi. ValueBasket ti invierà un' email informativa nel caso il tuo ordine venisse diviso, per confermare tempi di evasione e consegna. Questi cambiamenti verranno aggiornati sul tuo account, indicando i prodotti spediti e quelli da spedirsi in tempi brevi.
			<br /><br />
			<strong>Pagamento per gli Acquisti : </strong>
			Il pagamento dei prodotti ordinati deve essere effettuato al momento in cui l'ordine e confermato. ValueBasket.com offre, presso il punto cassa, vari metodi di pagamento come carte di credito e altri metodi di pagamento popolari per i clienti di effettuare il pagamento per i loro articoli ordinati. Si accetta la responsabilita di pagare tutti i costi e le spese connessi con i vostri articoli ordinati in relazione all'uso del metodo di pagamento che preferisci. Nel caso di eventuali transazioni non autorizzate apportate al tuo conto di pagamento da parte di terzi, sarai responsabile per gli importi fatturati. Se il pagamento per l'acquisto sul nostro sito web non e regolata a ValueBasket.com, si accetta di pagare tutte le somme dovute a ValueBasket.com.
			<br /><br />
			<strong>Accettazione dell'Ordine : </strong>
			Effettuando un ordine con, o fare un pagamento a, ValueBasket.com rappresenta la vostra offerta a noi per fare un acquisto degli articoli ordinati. ValueBasket.com mandera un'email a conferma della vostra offerta per confermare i dettagli dell'ordine.L'offerta di acquisto sara accettata dal ValueBasket.com quando spediamo il prodotto e la e-mail di conferma, come rappresentato da una mail di spedizione. Nel caso in cui il vostro ordine comprenda piu elementi, ogni elemento incluso nella vostra offerta di acquisto che non sara spedito e non incluso all'interno della email di spedizione, non sara incluso nel accettazione della vostra offerta di acquisto di tali articoli.
			<br /><br />
			<strong>Pre-Ordini : </strong>
			Quando nel vostro carrello ci saranno articoli "disponibili" affiancati ad articoli in "pre-ordine", gli articoli gia disponibili verranno spediti prima.
			<br /><br />
			<strong>Scambio di rischi : </strong>
			Tutti gli articoli acquistati presso, e si sono stabiliti i pagamenti, ValueBasket.com sono fatte in virtu i un contratto di spedizione. Cio significa che il rischio di perdita e il titolo per gli oggetti passano all'acquirente al momento della consegna al vettore selezionato da ValueBasket.com per consegnare il vostro ordine. Dove siete eleggibile per un rimborso per l'articolo restituito , ValueBasket.com non prende titolo per l'articolo restituito fino a quando l' articolo arriva al nostro prescritto indirizzo di restituzione con la debita autorizzazione e modulo compilato.rimborso puo essere elargito.
			<br /><br />
			<strong>Cancellazione, rimborsi e restituzione : </strong>
			E possibile inviare richieste di cancellazione via e-mail per il vostro ordine in qualsiasi momento prima della spedizione. Qualora sia stata effettuata la spedizione, e possibile richiedere un rimborso fino a 14 giorni dopo che le merci sono consegnate (a meno che il danno fisico viene trovato quando il vostro ordine e consegnato, e necessario informarci immediatamente), per presentare la richiesta, e sufficiente rivolgersi a avviare il processo. Dove si ha diritto a un rimborso, Valuebasket.com fornira l'autorizzazione ed un indirizzo di ritorno, se opportuno. La maggior parte delle richieste, che sono entro il periodo di 14 giorni e che sono: (i) per i nuovi articoli non aperti o (ii) hanno trovato essere difettoso sara eleggibile per un rimborso. La merce restituita per il rimborso devono essere nella condizione originale con tutto l'imballaggio originale, accessori e materiali inclusi. E necessario prendere tutte le precauzioni del bene e tornare nel suo stato originale.Dove gli acquisti sono aperti e sono costituiti da software utilizzabili, beni di consumo, o da elementi interessati da igiene, tali elementi non saranno rimborsabili. L'utente si impegna a sostenere le spese di restituzione del prodotto (s_. Il costo sostenuto per la restituzione della voce (s) puo essere oggetto di un rimborso se gli articoli_ si trovano ad essere difettosi e se la debita autorizzazione da ValueBasket.com e richiesta, a disposizione prima della restituzione della merce.
			<br /><br />
			Quando un rimborso è richiesto e l' idoneità è stata confermata secondo le Condizioni d' uso, procederemo il prima possibile al rimborso dell' importo corrispondente; questo richiede fino a 30 (trenta) giorni, dopo la conferma dell' idoneità, per riapparire sul tuo conto.
			<br /><br />
			<strong>Garanzie dei Prodotti : </strong>
			Tutti i prodotti, tranne per dove diversamente dichiarato, sono forniti con una garanzia di 36 mesi fornita da ValueBasket.com; tutti i prodotti inclusi nell'articolo, come batterie, salvaschermi, cavi etc., hanno una garanzia standard di 12 mesi. Dove e prevista una garanzia della casa produttrice del tuo prodotto, la garanzia del produttore sostituisce quella di ValueBasket.com. Una prova di acquisto deve essere fornita per poter godere della garanzia. Qualora un guasto con il vostro prodotto si verifica dopo 14 giorni dalla consegna ed entro il periodo di garanzia previsto, si puo inviare una richiesta al provider di garanzia per l'autorizzazione di una riparazione, sostituzione o rimborso (ad assoluta discrezione del provider di garanzia) per il vostro prodotto. Per iniziare il processo di richiesta di ammissibilita e di autorizzazione, e sufficiente contattarci <a href="[base_url;noerr;]contact">qui</a>; ValueBasket.com ti fornira quindi le istruzioni per procedere.Gli errori dovuti a incidente, negligenza o uso improprio non sono eleggibili per l'inclusione in garanzia. Dove si conferma che si e verificato un difetto di fabbricazione ed e coperto dalla garanzia, ValueBasket.com organizzera per una riparazione del prodotto e lo restituira a voi senza alcun costo.
			<br /><br />
			<strong>Esclusione della garanzia Limitazione di responsabilita : </strong>
			Questo sito e tutti informazioni, contenuti, materiali, prodotti (incluso il software) ED I SERVIZI INCLUSI o altrimenti rese disponibili a voi attraverso questo sito sono forniti dal VALUEBASTKET.COM "COME SONO" E "COME DISPONIBILE", se non diversamente fissato per iscritto. VALUEBASKET.COM NON FORNISCE ALCUNA DICHIARAZIONE O GARANZIA DI ALCUN TIPO, ESPRESSE O IMPLICITE, IN RELAZIONE AL FUNZIONAMENTO DI QUESTO SITO WEB O LE INFORMAZIONI, CONTENUTI, MATERIALI, PRODOTTI (incluso il software) o servizi compresi o altrimenti resi disponibili a voi attraverso questo sito, SE NON DIVERSAMENTE SPECIFICATO PER ISCRITTO.
			<br /><br />
			ValueBasket.com, il suo personale, gli obiettivi e le sue societa affiliate potranno essere ritenuti innocui e non saranno responsabili di eventuali danni, reclami, perdite, costi o spese di qualsiasi tipo derivanti dall'uso di questo sito o da qualsiasi mezzo di comunicazione con ValueBasket. com, o da qualsiasi informazione, contenuti, materiali, prodotti, (incluso il software) o servizi compresi o altrimenti rese disponibili a voi attraverso questo sito web.
			<br /><br />
			Voi accettate espressamete che l'utilizzo di questo sito web e avostro rischio.
			<br /><br />
			<strong>Ricorsi : </strong>
			Qualsiasi controversia o reclamo relativo in qualche modo alla vostra visita a nostro sito web o per i prodotti o servizi venduti o distribuiti da ValueBasket.com saranno oggetto di arbitrato vincolante riservato a Hong Kong, invece che in tribunale, tranne che? per i crediti in tribunale di modesta entita se le tue affermazioni si qualificano. L'arbitrato non include qualsiasi giudice o giuria, e la revisione della corte di un reparto di arbitrato e limitato. Tuttavia, un arbitro puo assegnare su base individuale gli stessi danni e sollievo, come un giudice (un provvedimento ingiuntivo e dichiarativo o danni previsti per legge), e deve seguire i termini di queste Condizioni di Utilizzo come una corte farebbe. L'arbitrato sara condotto, e i documenti presentati, in Inglese; o affiancati da una traduzione in inglese dei documenti. La sentenza emanata verra motivata dettagliatamente.
			<br /><br />
			<strong>Legge Applicabile : </strong>
			L'utente accetta che le leggi di Hong Kong governino queste Condizioni d'uso, per qualsiasi controversia di qualsiasi genere che potrebbero sorgere tra te e ValueBasket.com o delle sue affiliate.
			<br /><br />
			<strong>Politiche : </strong>
			Si prega di rivedere tutte le politiche ValueBasket.com pubblicate su questo sito. Queste politiche disciplinano anche la vostra visita a ValueBasket.com, quindi, verra considerato come aver accettato e di essere vincolato dalle politiche. Le presenti Condizioni di Utilizzo e Informativa sulla Privacy costituiscono l'intero Condizioni di utilizzo e sostituiscono tutte le altre condizioni, accordi o intese (orale o scritta) tra ValueBasket.com e l'utente relativamente alla materia trattata. Se una di queste condizioni venisse considerata non valida, nulla o per qualsiasi motivo inapplicabile, tale condizione e considerata separabile e non pregiudica la validita e l'applicabilita delle altre condizioni. Se si sceglie di lasciare il sito ValueBasket.com tramite link a siti diversi da ValueBasket.com, ValueBasket.com non e responsabile per le politiche sulla privacy di tali siti o dei cookie che quei siti web utilizzano.
			<br /><br />
			<strong>Assegnazioni : </strong>
			Accetti che queste Condizioni d'Uso e tutti gli accordi e le informazioni incorporate nel presente documento possono essere assegnati automaticamente da ValueBasket.com, a sua esclusiva discrezione,ad? una terza parte. L'utente non puo assegnare i suoi obblighi a terzi.
			<br /><br />
			<strong>Modifiche : </strong>
			ValueBasket.com si riserva il diritto, a sua esclusiva discrezione, di apportare modifiche al nostro sito, alle politiche e le presenti Condizioni d'Uso in qualsiasi momento. L'utente si impegna di accettare e di essere vincolato dalle nostre Condizioni d'uso, esposte nel nostro sito, navigando o comprando sul sito ValueBasket.com.
			<br /><br />
			<strong>Registrazione Azienda : </strong>
			ValueBasket.com ha uffici registrati<br>
			<table>
				<col width="20px"><col width="100px"><col>
				<tr>
					<td></td>
					<td>Hong Kong</td>
					<td>Unit 1505, 15/F, Yu Sung Boon Building, 107-111 Des Voeux Road Central</td>
				</tr>
			</table>
			<br /><br />
			il sito internete di ValueBasket.com si trova a <a href="[base_url;noerr;]">www.ValueBasket.com</a>.
			<br /><br />
		</p>
	</div>
</div>