CREATE TABLE `supplier_prod` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `supplier_id` int(10) unsigned NOT NULL,
  `prod_sku` bigint(20) unsigned NOT NULL,
  `currency_id` char(3) NOT NULL,
  `cost` decimal(15,2) NOT NULL,
  `pricehkd` decimal(15,2) NOT NULL,
  `lead_day` int(11) NOT NULL default 0,
  `moq` int(4) NOT NULL default 0,
  `location` varchar(4) NOT NULL DEFAULT '',
  `region` varchar(4) NOT NULL DEFAULT '',
  `surplus_qty` int(5) NOT NULL DEFAULT '0',
  `order_default` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '0 = Not Default / 1 = Default',
  `region_default` tinyint unsigned NOT NULL default '0',
  `supplier_status` varchar(2) NOT NULL DEFAULT 'A' COMMENT 'A = Readily Available / O = Temp Out of Stock',
  `comments` varchar(255) NOT  NULL DEFAULT '',
  `create_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` varchar(32) NOT NULL DEFAULT 'system',
  `modify_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` varchar(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_supplier_sku` (`supplier_id`,`prod_sku`, `order_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;