CREATE TABLE `promotion_code` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(20) NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `disc_type` varchar(2) NOT NULL COMMENT 'FD = Free Delivery / A = Amount / P = Percent / FI = Free Item / R = Redemption',
  `over_amount` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `over_amount_1` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `discount_1` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `over_amount_2` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `discount_2` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `over_amount_3` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `discount_3` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `over_amount_4` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `discount_4` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `over_amount_5` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `discount_5` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `region_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `country_id` char(2) NOT NULL DEFAULT '',
  `currency_id` char(3) NOT NULL DEFAULT '',
  `free_item_sku` char(11) NOT NULL DEFAULT '',
  `cat_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `sub_cat_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `sub_sub_cat_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `brand_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `relevant_prod` varchar(510) NOT NULL DEFAULT '',
  `email` varchar(255) NOT NULL DEFAULT '' COMMENT 'Client Email Address Matches',
  `disc_level` varchar(5) NOT NULL DEFAULT 'ALL' COMMENT 'ALL=ALL / BN=BRAND / CAT=CATEGORY / SCAT=SUB-CAT / SSCAT = SUB-SUB-CAT / PD = PRODUCT',
  `disc_level_value` varchar(510) NOT NULL DEFAULT '',
  `redemption_prod_value` varchar(100) NOT NULL DEFAULT '',
  `redemption_amount` double(15,2) unsigned NOT NULL DEFAULT '0.00',
  `promo_message` varchar(255) NOT NULL DEFAULT '',
  `display_message` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '1 = YES, 0 = NO',
  `expire_date` date NOT NULL DEFAULT '0000-00-00 00:00:00',
  `promotion_schedule` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '1 = YES, 0 = NO',
  `week_day` varchar(30) NOT NULL DEFAULT '',
  `start_time` time NOT NULL DEFAULT '00:00:00',
  `end_time` time NOT NULL DEFAULT '00:00:00',
  `time_zone` varchar(10) NOT NULL DEFAULT 'GTM+00:00',
  `repeat` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '1 = YES, 0 = NO',
  `redemption` mediumint(7) NOT NULL DEFAULT '-1' COMMENT 'Redemption per order: -1 = Unlimited',
  `total_redemption` mediumint(7) NOT NULL DEFAULT '-1' COMMENT 'Total Redemption: -1 = Unlimited',
  `no_taken` mediumint(7) NOT NULL DEFAULT '0',
  `status` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '0 = Inactive / 1 = Active',
  `create_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` varchar(32) NOT NULL DEFAULT 'system',
  `modify_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` varchar(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;