CREATE TABLE `country` (
  `id` int not null auto_increment,
  `country_id` char(2) NOT NULL COMMENT 'International country code (2 characters)',
  `id_3_digit` char(3) NOT NULL DEFAULT '',
  `name` varchar(32) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `status` tinyint(2) NOT NULL COMMENT '0 = Inactive, 1 = Active',
  `currency_id` char(3) NOT NULL,
  `language_id` varchar(16) NOT NULL DEFAULT '' COMMENT 'default language only',
  `fc_id` varchar(20) NOT NULL DEFAULT '',
  `allow_sell` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Allow selling to this country',
  `url_enable` tinyint(1) NOT NULL DEFAULT '0',
  `standalone` tinyint(1) NOT NULL DEFAULT '0',
  `create_on` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` INT(10) UNSIGNED NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` VARCHAR(32) NOT NULL DEFAULT 'system',
  `modify_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` INT(10) UNSIGNED NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` VARCHAR(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;