CREATE TABLE `currency` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `currency_id` char(3) NOT NULL,
  `sign` varchar(5) NOT NULL,
  `name` varchar(32) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `round_up` varchar(15) NOT NULL DEFAULT '',
  `round_up_nearest_for_price_table` float DEFAULT '0.99' COMMENT 'Only used for price table trigger',
  `sign_pos` char(1) NOT NULL DEFAULT '',
  `dec_place` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `dec_point` varchar(1) NOT NULL DEFAULT '',
  `thousands_sep` varchar(1) NOT NULL DEFAULT '',
  `create_on` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` INT(10) UNSIGNED NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` VARCHAR(32) NOT NULL DEFAULT 'system',
  `modify_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` INT(10) UNSIGNED NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` VARCHAR(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`),
  unique index idx_currency_id (currency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;