CREATE TABLE `platform_biz_var` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `selling_platform_id` VARCHAR(7) NOT NULL DEFAULT '',
  `need_round_nearest` CHAR(1) DEFAULT 'N',
  `latency_in_stock` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
  `latency_out_of_stock` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
  `vat_percent` DOUBLE(5,2) UNSIGNED DEFAULT '0.00',
  `admin_fee` DOUBLE(8,2) NOT NULL DEFAULT '0.00',
  `platform_region_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `platform_country_id` CHAR(2) NOT NULL,
  `dest_country` CHAR(2) NOT NULL COMMENT 'Destination Country',
  `platform_currency_id` CHAR(3) NOT NULL,
  `sign_pos` CHAR(1) NOT NULL DEFAULT '',
  `dec_place` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  `dec_point` VARCHAR(1) NOT NULL DEFAULT '',
  `thousands_sep` VARCHAR(1) NOT NULL DEFAULT '',
  `language_id` VARCHAR(16) NOT NULL DEFAULT 'en' COMMENT 'e.g. zh-cn, zh-tw, en and etc.',
  `payment_charge_percent` DOUBLE(4,2) UNSIGNED DEFAULT '0.00' COMMENT 'Payment charge percentage',
  `forex_fee_percent` DOUBLE(4,2) UNSIGNED DEFAULT '0.00' COMMENT 'Foreign exchange fee percentage',
  `delivery_type` VARCHAR(16) NOT NULL,
  `free_delivery_limit` DOUBLE DEFAULT '0' COMMENT 'Minimum purchase amount in order to receive free delivery',
  `default_shiptype` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `create_on` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` INT(10) UNSIGNED NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` VARCHAR(32) NOT NULL DEFAULT 'system',
  `modify_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` INT(10) UNSIGNED NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` VARCHAR(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;