CREATE TABLE `price_extend` (
  `id` int not null auto_increment,
  `sku` bigint(20) unsigned NOT NULL,
  `platform_id` varchar(7) NOT NULL,
  `title` varchar(255) NOT NULL DEFAULT '',
  `note` varchar(256) NOT NULL DEFAULT '' COMMENT 'Amazon: Condition note for ixten Product Feed',
  `ext_desc` text,
  `ext_ref_1` bigint(10) unsigned NOT NULL DEFAULT '0' COMMENT 'eBay: Category',
  `ext_ref_2` bigint(10) NOT NULL DEFAULT '0' COMMENT 'eBay: Category2',
  `ext_ref_3` varchar(64) NOT NULL DEFAULT '' COMMENT 'eBay: StoreCategory',
  `ext_ref_4` varchar(64) NOT NULL DEFAULT '' COMMENT 'eBay: StoreCategory2',
  `ext_qty` smallint(5) NOT NULL DEFAULT '0',
  `ext_item_id` varchar(32) NOT NULL DEFAULT '',
  `ext_condition` varchar(256) NOT NULL DEFAULT '' COMMENT 'Amazon: Condition for ixten Product Feed',
  `ext_status` varchar(2) NOT NULL DEFAULT '' COMMENT 'eBay: L = Listing, E = End',
  `fulfillment_centre_id` varchar(32) NOT NULL DEFAULT '' COMMENT 'Amazon: Fulfillment Centre ID for FBA',
  `amazon_reprice_name` varchar(64) NOT NULL DEFAULT '' COMMENT 'Amazon: Ixten Repricing Rule',
  `handling_time` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Specifies the maximum number of business days the seller commits to for preparing an item to be shipped after receiving a cleared payment',
  `action` varchar(2) NOT NULL DEFAULT '' COMMENT 'eBay: U = Update / Fnac: P = Update in Progress',
  `remark` varchar(64) NOT NULL DEFAULT '',
  `create_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` varchar(32) NOT NULL DEFAULT 'system',
  `modify_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` varchar(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`),
  unique key idx_sku_platform (`sku`,`platform_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;