CREATE TABLE `product_content` (
  `id` int not null auto_increment,
  `prod_sku` bigint unsigned NOT NULL,
  `lang_id` varchar(5) NOT NULL,
  `prod_name` varchar(255) NOT NULL DEFAULT '',
  `prod_name_original` tinyint(2) NOT NULL DEFAULT 0,
  `short_desc` text,
  `contents` text COMMENT 'Box Content / In the box',
  `contents_original` tinyint(2) NOT NULL DEFAULT 0 COMMENT '0 - machine translation 1 - manual translation',
  `series` varchar(255) NOT NULL DEFAULT '' COMMENT 'e.g. "Powershot"',
  `keywords` text,
  `keywords_original` tinyint(2) NOT NULL DEFAULT 0 COMMENT '0 - machine translation 1 - manual translation',
  `model_1` varchar(255) NOT NULL DEFAULT '' COMMENT 'for keywords creation',
  `model_2` varchar(255) NOT NULL DEFAULT '' COMMENT 'for keywords creation',
  `model_3` varchar(255) NOT NULL DEFAULT '' COMMENT 'for keywords creation',
  `model_4` varchar(255) NOT NULL DEFAULT '' COMMENT 'for keywords creation',
  `model_5` varchar(255) NOT NULL DEFAULT '' COMMENT 'for keywords creation',
  `detail_desc` text COMMENT 'Product Details',
  `detail_desc_original` tinyint(2) NOT NULL DEFAULT 0 COMMENT '0 - machine translation 1 - manual translation',
  `extra_info` tinytext,
  `website_status_long_text` text,
  `website_status_short_text` varchar(256) NOT NULL DEFAULT '',
  `youtube_id_1` varchar(128) NOT NULL DEFAULT '',
  `youtube_id_2` varchar(128) NOT NULL DEFAULT '',
  `youtube_caption_1` varchar(128) NOT NULL DEFAULT '',
  `youtube_caption_2` varchar(128) NOT NULL DEFAULT '',
  `create_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` varchar(32) NOT NULL DEFAULT 'system',
  `modify_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` varchar(32) NOT NULL DEFAULT 'system',
  PRIMARY key (id),
  unique key idx_sku_lang (`prod_sku`,`lang_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
