  CREATE TABLE `ra_product` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sku` char(15) NOT NULL,
  `rcm_group_id_1` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_1` int(2) NOT NULL DEFAULT '0' COMMENT '1st priority, >0: ra_group id',
  `rcm_group_id_2` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_2` int(2) NOT NULL DEFAULT '0' COMMENT '2nd priority: >0: ra_group id',
  `rcm_group_id_3` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_3` int(2) NOT NULL DEFAULT '0' COMMENT '3rd priority, >0: ra_group id',
  `rcm_group_id_4` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_4` int(2) NOT NULL DEFAULT '0' COMMENT '4th priority,  >0: ra_group id',
  `rcm_group_id_5` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_5` int(2) NOT NULL DEFAULT '0' COMMENT '5th priority, >0: ra_group id',
  `rcm_group_id_6` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_6` int(2) NOT NULL DEFAULT '0' COMMENT '6th priority, >0: ra_group id',
  `rcm_group_id_7` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_7` int(2) NOT NULL DEFAULT '0' COMMENT '7th priority, >0: ra_group id',
  `rcm_group_id_8` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_8` int(2) NOT NULL DEFAULT '0' COMMENT '8th priority,  >0: ra_group id',
  `rcm_group_id_9` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_9` int(2) NOT NULL DEFAULT '0' COMMENT '9th priority,  >0: ra_group id',
  `rcm_group_id_10` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_10` int(2) NOT NULL DEFAULT '0' COMMENT '10th priority, >0: ra_group id',
  `rcm_group_id_11` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_11` int(2) NOT NULL DEFAULT '0' COMMENT '11th priority, >0: ra_group id',
  `rcm_group_id_12` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_12` int(2) NOT NULL DEFAULT '0' COMMENT '12th priority, >0: ra_group id',
  `rcm_group_id_13` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_13` int(2) NOT NULL DEFAULT '0' COMMENT '13th priority, >0: ra_group id',
  `rcm_group_id_14` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_14` int(2) NOT NULL DEFAULT '0' COMMENT '14th priority, >0: ra_group id',
  `rcm_group_id_15` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_15` int(2) NOT NULL DEFAULT '0' COMMENT '15th priority, >0: ra_group id',
  `rcm_group_id_16` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_16` int(2) NOT NULL DEFAULT '0' COMMENT '16th priority, >0: ra_group id',
  `rcm_group_id_17` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_17` int(2) NOT NULL DEFAULT '0' COMMENT '17th priority, >0: ra_group id',
  `rcm_group_id_18` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_18` int(2) NOT NULL DEFAULT '0' COMMENT '18th priority, >0: ra_group id',
  `rcm_group_id_19` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_19` int(2) NOT NULL DEFAULT '0' COMMENT '19th priority, >0: ra_group id',
  `rcm_group_id_20` bigint(20) NOT NULL DEFAULT '0',
  `bundle_use_20` int(2) NOT NULL DEFAULT '0' COMMENT '20th priority, >0: ra_group id',
  `create_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` varchar(32) NOT NULL DEFAULT 'system',
  `modify_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` varchar(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;