CREATE TABLE `refund_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `refund_id` BIGINT(20) UNSIGNED NOT NULL,
  `line_no` SMALLINT(3) UNSIGNED NOT NULL,
  `item_sku` VARCHAR(15) NOT NULL DEFAULT '',
  `qty` SMALLINT(5) UNSIGNED NOT NULL,
  `refund_amount` FLOAT(10,2) UNSIGNED NOT NULL DEFAULT '0.00',
  `status` VARCHAR(2) NOT NULL DEFAULT 'CS' COMMENT 'N - NEW, CS - CS, CP - COMPLIANCE, LG - LOGISTICS, AC- ACCOUNT, D - DENIED, C - COMPLETED',
  `refund_type` CHAR(1) NOT NULL DEFAULT 'C' COMMENT 'C- Cashback, R- Refund',
  `item_status` CHAR(1) NOT NULL DEFAULT '' COMMENT 'N - New Product, U - Used (2nd Hand), M - Missing Item',
  `stockback_date` DATE  NOT NULL DEFAULT '0000-00-00 00:00:00',
  `stockback_warehouse` VARCHAR(20) NOT NULL DEFAULT '',
  `create_on` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` INT(10) UNSIGNED NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` VARCHAR(32) NOT NULL DEFAULT 'system',
  `modify_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` INT(10) UNSIGNED NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` VARCHAR(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`),
  UNIQUE KEY idx_refund_line_sku (`refund_id`,`line_no`,`item_sku`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;