CREATE TABLE `so_item` (
  `id` int not null auto_increment,
  `so_no` char(8) NOT NULL,
  `line_no` smallint(5) unsigned NOT NULL,
  `prod_sku` varchar(15) NOT NULL,
  `prod_name` varchar(255) NOT NULL DEFAULT '',
  `ext_item_cd` varchar(255) NOT NULL DEFAULT '',
  `qty` smallint(5) unsigned NOT NULL,
  `unit_price` double(15,2) unsigned NOT NULL,
  `vat_total` double(15,2) unsigned NOT NULL,
  `gst_total` double(15,2) unsigned DEFAULT '0.00',
  `amount` double(15,2) unsigned NOT NULL,
  `website_status` varchar(2) NOT NULL DEFAULT '',
  `warranty_in_month` smallint(2) NOT NULL DEFAULT '0',
  `status` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '0 = Not Shipped / 1 = Shipped',
  `create_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` varchar(32) NOT NULL DEFAULT 'system',
  `modify_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` varchar(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`),
  unique KEY idx_so_item (`so_no`,`line_no`,`prod_sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;