CREATE TABLE `so_item_detail` (
  `id` int not null auto_increment,
  `so_no` char(8) NOT NULL,
  `line_no` smallint(5) unsigned NOT NULL,
  `item_sku` varchar(15) NOT NULL,
  `qty` smallint(5) unsigned NOT NULL,
  `outstanding_qty` smallint(5) unsigned NOT NULL,
  `unit_price` double(15,2) unsigned NOT NULL,
  `vat_total` double(15,2) unsigned NOT NULL,
  `gst_total` double(15,2) unsigned DEFAULT '0.00',
  `discount_total` double(15,2) DEFAULT '0.00' COMMENT 'Total bundle discount amt (discount_total+amount = original selling pr)',
  `discount` double(4,2) unsigned NOT NULL DEFAULT '0.00' COMMENT 'Discount % in Bundle (not in use;can''t calc raw margin)',
  `bundle_core_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'bundle_core_id used',
  `bundle_level` varchar(2) NOT NULL DEFAULT '' COMMENT '0=CoreSKU / 1=bundle''s component',
  `amount` double(15,2) unsigned NOT NULL,
  `promo_disc_amt` double(15,2) unsigned NOT NULL DEFAULT '0.00' COMMENT 'Discount Amount in promotion',
  `cost` double(15,2) unsigned NOT NULL,
  `item_unit_cost` double(15,2) NOT NULL DEFAULT '0.00',
  `profit` double(15,2) NOT NULL DEFAULT '0.00',
  `profit_raw` double(15,2) NOT NULL DEFAULT '0.00' COMMENT 'profit w/o promo',
  `margin` double(15,2) NOT NULL DEFAULT '0.00',
  `margin_raw` double(15,2) NOT NULL DEFAULT '0.00' COMMENT 'margin w/o promo',
  `status` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '0 = Not Shipped / 1 = Shipped',
  `create_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` varchar(32) NOT NULL DEFAULT 'system',
  `modify_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` varchar(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`),
  unique KEY idx_so_item_detail (`so_no`,`line_no`,`item_sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;