CREATE TABLE `so_payment_status` (
  `id` int not null auto_increment,
  `so_no` char(8) NOT NULL,
  `payment_gateway_id` varchar(20) NOT NULL DEFAULT '',
  `pay_to_account` varchar(64) NOT NULL DEFAULT '',
  `card_id` varchar(20) NOT NULL DEFAULT '',
  `payment_status` varchar(2) DEFAULT 'N' COMMENT 'N = New / P = Processing / S = Successed / C = Cancelled / F = Failed / B = Chargeback / CF = Cancel Failed',
  `remark` text,
  `mac_token` varchar(64) NOT NULL DEFAULT '' COMMENT 'MAC / TOKEN Checking',
  `retry` smallint(2) NOT NULL DEFAULT '0',
  `payer_email` varchar(255) NOT NULL DEFAULT '' COMMENT 'Email address in payment gateway',
  `payer_ref` varchar(64) NOT NULL DEFAULT '' COMMENT 'PayPal:PAYERID',
  `risk_ref1` varchar(256) NOT NULL DEFAULT '' COMMENT 'PayPal:PROTECTIONELIGIBILITY / GlobalCollect:AVSRESULT / MoneyBookers: VERIFICATIONLEVEL / Adyen:3DAUTHENTICATIONRESULT',
  `risk_ref2` varchar(64) NOT NULL DEFAULT '' COMMENT 'PayPal:PROTECTIONELIGIBILITYTYPE / GlobalCollect:FRAUDRESULT, AltaPay:FraudRiskScore, Adyen:FraudScore',
  `risk_ref3` varchar(64) NOT NULL DEFAULT '' COMMENT 'PayPal:ADDRESSSTATUS, AltaPay:FraudRecommendation, Adyen:AuthorisationCode',
  `risk_ref4` varchar(256) NOT NULL DEFAULT '' COMMENT 'PayPal:PAYERSTATUS, AltaPay:FraudExplanation, Adyen:RefusalReason',
  `pay_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `pending_action` varchar(2) NOT NULL DEFAULT '' COMMENT 'C = Cancel Payment / R = Reject Challenged / P = Process Challenged / C = Cancel Payment / R = Reject Challenged / CC = Credit Check Pending / NA = No more action',
  `create_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `create_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address, default 127.0.0.1',
  `create_by` varchar(32) NOT NULL DEFAULT 'system',
  `modify_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_at` int(10) unsigned NOT NULL DEFAULT '2130706433' COMMENT 'IP address',
  `modify_by` varchar(32) NOT NULL DEFAULT 'system',
  PRIMARY KEY (`id`),
  unique KEY idx_so_payment_status (`so_no`,`payment_gateway_id`,`pay_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;